name: CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sep4frontendapp  # set this to the name of your Azure Web App for the frontend
  AZURE_RESOURCE_GROUP: sep4resource  # set this to the name of your Azure Resource Group
  AZURE_CONTAINER_REGISTRY: sep4backendregistry.azurecr.io  # set this to the login server of your Azure Container Registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t sep4backendregistry.azurecr.io/proxy:latest -f proxy/Dockerfile --no-cache .

      - name: Push Docker image
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/proxy:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure WebApp Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}/proxy:latest
